#version: '3'
#
#services:
#  docker-mysql:
#    image: mysql:8.0.11
#    environment:
#      - MYSQL_ROOT_PASSWORD=test
#      - MYSQL_DATABASE=nc1_test
#      - MYSQL_USER=test
#      - MYSQL_PASSWORD=test
#
#  spring-boot-jpa-docker-webapp:
#    image: deepti/spring-boot-docker
#    depends_on:
#      - docker-mysql
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_HOST=nc1_test
#      - DATABASE_USER=test
#      - DATABASE_PASSWORD=test
#      - DATABASE_NAME=nc1_test
#      - DATABASE_PORT=3306

services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=nc1_test'
#      - 'MYSQL_PASSWORD=test'
#      - 'MYSQL_ROOT_PASSWORD=test'
#      - 'MYSQL_USER=test'
#    ports:
#      - '3306'

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: nc1_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"